from fastapi import Depends, FastAPI, HTTPException
from pydantic import BaseModel, Field
from contextlib import asynccontextmanager
from config import settings
from logger import logger, request_id_context
import uuid
import time

from agent_factory import create_agent

@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.agent = create_agent()

    yield

    app.state.agent = None

app = FastAPI(
    title="EhsaN AI Agent",
    lifespan=lifespan
)

def get_agent():
    return app.state.agent





class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        description="User message sent to the EhSaN AI Agent."
    )

@app.middleware("http")
async def add_request_id(request, call_next):
    request_id = str(uuid.uuid4())

    request.state.request_id = request_id

    token = request_id_context.set(request_id)

    start_time = time.perf_counter()

    logger.info(
        f"Request started | request_id={request_id} | "
        f"method={request.method} | path={request.url.path}"
    )

    try:
        response = await call_next(request)

        duration = time.perf_counter() - start_time

        logger.info(
            f"Request finished | request_id={request_id} | "
            f"status_code={response.status_code} | "
            f"duration={duration:.4f}s"
        )

        response.headers["X-Request-ID"] = request_id

        return response

    finally:
        request_id_context.reset(token)
        
@app.get("/")
def root():
    return {
        "message": "EhsaN AI Agent API is running."
    }
class HealthResponse(BaseModel):
    status: str
    agent: str
    model: str
    environment: str

@app.get("/health", response_model=HealthResponse)
def health():
    return {
        "status": "healthy",
        "agent": "EhSaN",
        "model": settings.OPENAI_MODEL,
        "environment": settings.ENVIRONMENT
    }

class ChatResponse(BaseModel):
    response: str = Field(
        ...,
        description="Response generated by the EhSaN AI Agent."
    )

@app.post(
    "/chat",
    response_model=ChatResponse,
    summary="Chat with EhSaN AI Agent",
    description="Send a message to the EhSaN AI Agent and receive an AI-generated response."
)
def chat(
    request: ChatRequest,
    agent=Depends(get_agent)
):
    try:
        response = agent.run(request.message)
        return {
            "response": response
        }
    except Exception:
        raise HTTPException(
            status_code=500,
            detail="An internal error occurred."
        )

